/**
 * Slide Deck Cleaner - 本地测试服务器
 */

const http = require('http');
const AdmZip = require('adm-zip');

const PORT = 5000;

// 预置水印关键词
const WATERMARK_KEYWORDS = [
  "NotebookLM",
  "Made with Gamma",
  "Gamma",
  "beautiful.ai",
  "Canva",
  "AiPPT",
  "通义万相",
  "讯飞智文",
  "AI PPT",
  "Generated by",
];

function cleanPPTX(buffer) {
  const zip = new AdmZip(buffer);
  let removedCount = 0;
  
  const entries = zip.getEntries();
  
  entries.forEach(entry => {
    if (entry.entryName.endsWith('.xml') && (
      entry.entryName.startsWith('ppt/slides/') ||
      entry.entryName.startsWith('ppt/slides/master/') ||
      entry.entryName.startsWith('ppt/theme/')
    )) {
      let content = entry.getData().toString('utf8');
      const originalLen = content.length;
      
      WATERMARK_KEYWORDS.forEach(keyword => {
        const regex = new RegExp(`<a:t>[^<]*${keyword}[^<]*</a:t>`, 'gi');
        content = content.replace(regex, '');
        const wRegex = new RegExp(`<w:t>[^<]*${keyword}[^<]*</w:t>`, 'gi');
        content = content.replace(wRegex, '');
      });
      
      removedCount += originalLen - content.length;
      entry.setData(content);
    }
  });
  
  return { zip, removedCount };
}

function parseMultipart(buffer, boundary) {
  const parts = [];
  const boundaryBuffer = Buffer.from('--' + boundary);
  let start = 0;
  
  while (start < buffer.length) {
    const idx = buffer.indexOf(boundaryBuffer, start);
    if (idx === -1) break;
    
    if (start > 0) {
      const partData = buffer.slice(start, idx);
      const headerEnd = partData.indexOf(Buffer.from('\r\n\r\n'));
      if (headerEnd > 0) {
        const headers = partData.slice(0, headerEnd).toString();
        const content = partData.slice(headerEnd + 4, partData.length - 2);
        
        const filenameMatch = headers.match(/filename="([^"]+)"/);
        if (filenameMatch) {
          parts.push({
            filename: filenameMatch[1],
            data: content
          });
        }
      }
    }
    start = idx + boundaryBuffer.length + 2;
  }
  
  return parts;
}

const HTML = `<!DOCTYPE html>
<html lang="zh">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Slide Deck Cleaner - PPT 水印清除</title>
  <script src="https://cdn.tailwindcss.com"></script>
</head>
<body class="bg-gray-50 min-h-screen">
  <div class="max-w-xl mx-auto mt-20 p-8">
    <h1 class="text-3xl font-bold text-center text-gray-800 mb-2">🧹 Slide Deck Cleaner</h1>
    <p class="text-center text-gray-600 mb-8">批量清除 PPTX 文件中的水印</p>
    
    <div class="bg-white rounded-lg shadow-lg p-8">
      <form method="post" enctype="multipart/form-data" id="uploadForm">
        <label class="border-2 border-dashed border-gray-300 rounded-lg p-8 block text-center cursor-pointer hover:border-blue-500 transition-colors">
          <input type="file" name="file" accept=".pptx" multiple required class="hidden" id="fileInput">
          <div class="text-gray-600">📁 点击选择或拖拽 PPTX 文件</div>
          <div class="text-gray-400 text-sm mt-2">支持批量上传</div>
        </label>
        
        <div id="fileList" class="mt-4 space-y-2"></div>
        
        <button type="submit" class="w-full bg-blue-500 text-white py-3 rounded-lg mt-6 hover:bg-blue-600 transition-colors font-medium">
          清除水印
        </button>
      </form>
      
      <div class="mt-6 bg-gray-50 rounded-lg p-4">
        <strong class="text-gray-700">支持的水印来源：</strong>
        <div class="text-gray-500 text-sm mt-2">${WATERMARK_KEYWORDS.join(', ')}</div>
      </div>
    </div>
  </div>
  
  <script>
    const fileInput = document.getElementById('fileInput');
    const fileList = document.getElementById('fileList');
    
    fileInput.addEventListener('change', () => {
      fileList.innerHTML = Array.from(fileInput.files).map(f => 
        '<div class="bg-gray-100 px-4 py-2 rounded text-sm">' + f.name + '</div>'
      ).join('');
    });
  </script>
</body>
</html>`;

const server = http.createServer((req, res) => {
  if (req.method === 'GET') {
    res.writeHead(200, { 'Content-Type': 'text/html' });
    res.end(HTML);
    return;
  }
  
  if (req.method === 'POST') {
    let body = [];
    req.on('data', chunk => body.push(chunk));
    req.on('end', () => {
      const buffer = Buffer.concat(body);
      const contentType = req.headers['content-type'];
      
      if (!contentType || !contentType.includes('multipart')) {
        res.writeHead(400, { 'Content-Type': 'text/plain' });
        res.end('请上传文件');
        return;
      }
      
      const boundary = contentType.split('boundary=')[1];
      const files = parseMultipart(buffer, boundary);
      
      if (files.length === 0) {
        res.writeHead(400, { 'Content-Type': 'text/plain' });
        res.end('请上传文件');
        return;
      }
      
      if (files.length === 1) {
        const { zip, removedCount } = cleanPPTX(files[0].data);
        const outputBuffer = zip.toBuffer();
        
        res.writeHead(200, {
          'Content-Type': 'application/vnd.openxmlformats-officedocument.presentationml.presentation',
          'Content-Disposition': `attachment; filename="cleaned_${files[0].filename}"`,
          'X-Removed-Count': removedCount
        });
        res.end(outputBuffer);
      } else {
        const output = new AdmZip();
        files.forEach(file => {
          const { zip } = cleanPPTX(file.data);
          const zipBuffer = zip.toBuffer();
          output.addFile(`cleaned_${file.filename}`, zipBuffer);
        });
        
        res.writeHead(200, {
          'Content-Type': 'application/zip',
          'Content-Disposition': 'attachment; filename="cleaned_files.zip"'
        });
        res.end(output.toBuffer());
      }
    });
    return;
  }
  
  res.writeHead(404);
  res.end();
});

server.listen(PORT, () => {
  console.log(\`🚀 测试服务器: http://localhost:\${PORT}\`);
});
