"use client";

import { useState } from "react";

export default function Home() {
  const [files, setFiles] = useState<File[]>([]);
  const [uploading, setUploading] = useState(false);
  const [result, setResult] = useState<{ name: string; removed: number }[]>([]);

  const handleFileChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    if (e.target.files) {
      setFiles(Array.from(e.target.files));
      setResult([]);
    }
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (files.length === 0) return;

    setUploading(true);
    setResult([]);

    const formData = new FormData();
    files.forEach((file) => formData.append("file", file));

    try {
      const response = await fetch("/api/clean", {
        method: "POST",
        body: formData,
      });

      if (!response.ok) {
        const error = await response.json();
        alert(error.error || "上传失败");
        setUploading(false);
        return;
      }

      // 处理文件下载
      const contentDisposition = response.headers.get("Content-Disposition");
      let filename = "cleaned_files.zip";
      if (contentDisposition && contentDisposition.includes("filename=")) {
        filename = contentDisposition.split("filename=")[1].replace(/"/g, "");
      }

      const blob = await response.blob();
      const url = window.URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = filename;
      document.body.appendChild(a);
      a.click();
      window.URL.revokeObjectURL(url);
      document.body.removeChild(a);

      // 解析结果
      const removed = response.headers.get("X-Removed-Count") || "0";
      setResult(files.map((f) => ({ name: f.name, removed: parseInt(removed) })));
    } catch (error) {
      console.error(error);
      alert("处理失败");
    }

    setUploading(false);
  };

  return (
    <div className="min-h-screen bg-gray-50 flex items-center justify-center p-4">
      <div className="max-w-xl w-full">
        <div className="text-center mb-8">
          <h1 className="text-4xl font-bold text-gray-800 mb-2">🧹 Slide Deck Cleaner</h1>
          <p className="text-gray-600">批量清除 PPTX 文件中的水印</p>
        </div>

        <div className="bg-white rounded-xl shadow-lg p-8">
          <form onSubmit={handleSubmit}>
            <label className="border-2 border-dashed border-gray-300 rounded-lg p-8 block text-center cursor-pointer hover:border-blue-500 hover:bg-blue-50 transition-all">
              <input
                type="file"
                accept=".pptx"
                multiple
                onChange={handleFileChange}
                className="hidden"
              />
              <div className="text-gray-600 text-lg">
                📁 点击选择或拖拽 PPTX 文件
              </div>
              <div className="text-gray-400 text-sm mt-2">支持批量上传多个文件</div>
            </label>

            {files.length > 0 && (
              <div className="mt-4 space-y-2">
                {files.map((file, index) => (
                  <div
                    key={index}
                    className="bg-gray-100 px-4 py-2 rounded-lg text-sm text-gray-700 flex items-center gap-2"
                  >
                    <span>📄</span>
                    <span className="truncate">{file.name}</span>
                    <span className="text-gray-400 text-xs">
                      ({(file.size / 1024).toFixed(1)} KB)
                    </span>
                  </div>
                ))}
              </div>
            )}

            <button
              type="submit"
              disabled={files.length === 0 || uploading}
              className="w-full bg-blue-500 text-white py-3 rounded-lg mt-6 hover:bg-blue-600 disabled:bg-gray-300 disabled:cursor-not-allowed transition-colors font-medium"
            >
              {uploading ? "处理中..." : "清除水印"}
            </button>
          </form>

          {result.length > 0 && (
            <div className="mt-6 bg-green-50 border border-green-200 rounded-lg p-4">
              <div className="text-green-700 font-medium mb-2">✅ 处理完成</div>
              {result.map((r, i) => (
                <div key={i} className="text-sm text-green-600">
                  {r.name} - 移除 {r.removed} 处水印
                </div>
              ))}
            </div>
          )}

          <div className="mt-6 bg-gray-50 rounded-lg p-4">
            <div className="text-gray-700 font-medium mb-2">支持的水印来源：</div>
            <div className="text-gray-500 text-sm">
              NotebookLM, Made with Gamma, Gamma, beautiful.ai, Canva, AiPPT,
              通义万相, 讯飞智文, AI PPT, Generated by
            </div>
          </div>
        </div>

        <div className="text-center mt-6 text-gray-400 text-sm">
          Powered by Next.js + Tailwind CSS
        </div>
      </div>
    </div>
  );
}
