import { NextRequest, NextResponse } from 'next/server';
import AdmZip from 'adm-zip';

// 预置水印关键词
const WATERMARK_KEYWORDS = [
  "NotebookLM",
  "Made with Gamma",
  "Gamma",
  "beautiful.ai",
  "Canva",
  "AiPPT",
  "通义万相",
  "讯飞智文",
  "AI PPT",
  "Generated by",
];

function cleanPPTX(buffer: Buffer) {
  const zip = new AdmZip(buffer);
  let removedCount = 0;
  
  const entries = zip.getEntries();
  
  entries.forEach((entry) => {
    if (entry.entryName.endsWith('.xml') && (
      entry.entryName.startsWith('ppt/slides/') ||
      entry.entryName.startsWith('ppt/slides/master/') ||
      entry.entryName.startsWith('ppt/theme/')
    )) {
      let content = entry.getData().toString('utf8');
      const originalLen = content.length;
      
      WATERMARK_KEYWORDS.forEach((keyword) => {
        const regex = new RegExp(`<a:t>[^<]*${keyword}[^<]*</a:t>`, 'gi');
        content = content.replace(regex, '');
        const wRegex = new RegExp(`<w:t>[^<]*${keyword}[^<]*</w:t>`, 'gi');
        content = content.replace(wRegex, '');
      });
      
      removedCount += originalLen - content.length;
      entry.setData(content);
    }
  });
  
  return { zip, removedCount };
}

export async function POST(request: NextRequest) {
  const formData = await request.formData();
  const files = formData.getAll('file') as File[];
  
  if (!files || files.length === 0) {
    return NextResponse.json({ error: '请上传文件' }, { status: 400 });
  }
  
  if (files.length === 1) {
    const file = files[0];
    const arrayBuffer = await file.arrayBuffer();
    const buffer = Buffer.from(arrayBuffer);
    
    const { zip, removedCount } = cleanPPTX(buffer);
    const outputBuffer = zip.toBuffer();
    
    return new NextResponse(outputBuffer, {
      headers: {
        'Content-Type': 'application/vnd.openxmlformats-officedocument.presentationml.presentation',
        'Content-Disposition': `attachment; filename="cleaned_${file.name}"`,
        'X-Removed-Count': String(removedCount),
      },
    });
  } else {
    // 批量处理
    const output = new AdmZip();
    
    for (const file of files) {
      const arrayBuffer = await file.arrayBuffer();
      const buffer = Buffer.from(arrayBuffer);
      const { zip } = cleanPPTX(buffer);
      const zipBuffer = zip.toBuffer();
      output.addFile(`cleaned_${file.name}`, zipBuffer);
    }
    
    return new NextResponse(output.toBuffer(), {
      headers: {
        'Content-Type': 'application/zip',
        'Content-Disposition': 'attachment; filename="cleaned_files.zip"',
      },
    });
  }
}

export async function GET() {
  return NextResponse.json({
    message: 'Slide Deck Cleaner API',
    keywords: WATERMARK_KEYWORDS,
  });
}
